import type { Metadata } from 'next';
import './globals.scss';
import { getClient } from '@/utils/serverClient';
import { Header } from '@/components/header';
import '@/styles/main.scss';
import { MenuDocument, MenuQuery } from '@/graphql/generated/graphql';
import { Footer } from '@/components/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = getClient();
  const menu = await client.query<MenuQuery>({
    query: MenuDocument,
    context: {
      fetchOptions: {
        // Figure out this tag nonsense
        // next: { tags: ['mainmenu'] },
      },
    },
  });
  return (
    <html lang='en'>
      <body>
        <Header menu={menu.data.allCategoryPages} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
